### ISSUE TITLE
Archetype tutorial series idea

### ISSUE THREAD

**Issue by branflake2267** [ArcBees/Arcbees-Archetypes#59]
I was thinking about tutorials and was wondering if an GWTP Archetype tutorial series would be useful. My thought is, tutorial walk though coupled with Archetype download, which would give a person a try the step in the tutorial. Taking even further, would be cool to initiate form a IDE plugin, as a help tutorial. Anyway, thought I'd share the idea.

**Comment by olafleur** [comment]
The tutorials will come in the weeks/months to come. Please try the new AppEngine archetype. If you still have problems with it, please tell! ;-)
