### ISSUE TITLE
Superdev mode

### ISSUE THREAD

**Issue by dmg46664** [ArcBees/Arcbees-Archetypes#92]
Maybe this is easy, but I thought it would be nice if the poms were set up with super-dev mode.

I just managed to get the WebApplication to run after a pom install. I had some issues, because I have Java8 set up as default. That was a problem that doesn't announce itself but the server doesn't run.

http://stackoverflow.com/questions/22520903/cant-start-google-web-app-in-eclipse-security-restrictions-will-not-be-complete

Okay, so I fixed this and now I find the gwtdev plugin doesn't install in chrome or firefox, and not working for me in IE either. 

https://code.google.com/p/google-web-toolkit/issues/detail?id=7778#c5

Apparently there are work arounds, but I was wondering since superdev mode is being espoused as the future, it would be great if it was set up by default in the maven solution.

Has felt like a big chore just to get to a hello world point.

**Comment by olafleur** [comment]
It should be straightforward with the up-to-date archetypes. If you need help with the SuperDev Mode or other things, feel free to ask!
