### ISSUE TITLE
Archetype dependencies are out of date

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/Arcbees-Archetypes#97]
Haven't gone through them all but at least the gwtp-appengine-objectify archetype is using v1.2.1 of GWTP and 4.03b of Objectfity.

All archetypes should be updated or they should be deprecated.

Maybe we should compress everything into a single simple archetype?

**Comment by olafleur** [comment]
Now we have two simple archetypes. I think that their dependencies are up-to-date. Feel free to reopen if that's not the case.
