### ISSUE TITLE
GWTP-Basic has pom.xml error

### ISSUE THREAD

**Issue by branflake2267** [ArcBees/Arcbees-Archetypes#98]
Please remove this in gwtp-basic. 
```
    <configuration>
        <additionalProjectnatures>
            <projectnature>com.arcbees.plugin.eclipse.nature.GWTPNature</projectnature>
        </additionalProjectnatures>
    </configuration>
```

**Comment by branflake2267** [comment]
I suspect this has to be added to the m2e plugin lifecycle instead.

**Comment by branflake2267** [comment]
![screen shot 2015-01-27 at 4 17 33 pm](https://cloud.githubusercontent.com/assets/1326504/5920880/39bb04a8-a640-11e4-83f4-847985048363.png)

**Comment by olafleur** [comment]
Closing as it was removed, I think (cannot find it).
